"""add embedding to document_chunks

Revision ID: 4631c50f7fca
Revises: 53be5709c8c0
Create Date: 2026-03-17 09:13:08.867106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = "4631c50f7fca"
down_revision: Union[str, None] = "53be5709c8c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.add_column(
        "document_chunks", sa.Column("embedding", Vector(dim=384), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "embedding")
    # ### end Alembic commands ###
