"""add ingest structure fields

Revision ID: 40db10362ce2
Revises: eb036bfc5e8b
Create Date: 2026-03-20 07:41:43.850676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40db10362ce2'
down_revision: Union[str, None] = 'eb036bfc5e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('section_heading', sa.String(length=500), nullable=True))
    op.add_column('document_chunks', sa.Column('heading_level', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('chunk_type', sa.String(length=50), nullable=True))
    op.add_column('document_chunks', sa.Column('content_language', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('parser_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('parser_version', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('content_language', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_language')
    op.drop_column('documents', 'parser_version')
    op.drop_column('documents', 'parser_type')
    op.drop_column('document_chunks', 'content_language')
    op.drop_column('document_chunks', 'chunk_type')
    op.drop_column('document_chunks', 'heading_level')
    op.drop_column('document_chunks', 'section_heading')
    # ### end Alembic commands ###
